version: '3'
volumes:
  mongo:
    driver: local
services:
### MongoDB ##############################################
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
### Backend ##############################################
  user-services:
    image: fernandowahl/user-services
    ports:
      - "40002:40002"
    depends_on:
      - mongo
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure
