version: '3'
volumes:
  mongo:
    driver: local
services:
### MongoDB ##############################################
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
### Backend ##############################################
  user-services:
    image: fernandowahl/api
    ports:
      - "40002:40002"
    depends_on:
      - mongo
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure
### Viewer ##############################################
  user-services:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure